# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_by', to='blog.Blog'),
        ),
    ]
